/**
 * This file was generated by the JPA Modeler
 */

package de.arstulke.model;

import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import java.io.Serializable;

/**
 * @author ARSTULKE
 */

@Entity
public class Card implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String text;

    @Basic
    private String backgroundColor;

    @Basic
    private String textColor;

    @Embedded
    private Position position;

    @OneToOne(targetEntity = CardBoard.class, fetch = FetchType.LAZY)
    private CardBoard cardBoard;

    public Card(String text, Position position, String backgroundColor, String textColor) {
        this(text, position);
        this.backgroundColor = backgroundColor;
        this.textColor = textColor;
    }

    public Card(String text, Position position) {
        this.text = text;
        this.position = position;
    }

    public Card() {
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getBackgroundColor() {
        return this.backgroundColor;
    }

    public void setBackgroundColor(String backgroundColor) {
        this.backgroundColor = backgroundColor;
    }

    public String getTextColor() {
        return this.textColor;
    }

    public void setTextColor(String textColor) {
        this.textColor = textColor;
    }

    public Position getPosition() {
        return position;
    }

    public void setPosition(Position position) {
        this.position = position;
    }

    @JsonIgnore
    public CardBoard getCardBoard() {
        return cardBoard;
    }

    public void setCardBoard(CardBoard cardBoard) {
        this.cardBoard = cardBoard;
    }

    @Override
    public String toString() {
        return "Card{" +
                "id=" + id +
                ", text='" + text + '\'' +
                ", backgroundColor='" + backgroundColor + '\'' +
                ", textColor='" + textColor + '\'' +
                ", position=" + position +
                '}';
    }

    public String forLogging() {
        int end = text.length() < 35 ? text.length() : 35;
        String text = this.text.substring(0, end) + "...";
        return "Card{" +
                "id=" + id +
                ", text='" + text + '\'' +
                ", backgroundColor='" + backgroundColor + '\'' +
                ", textColor='" + textColor + '\'' +
                ", position=" + position +
                '}';
    }
}
